name: "Rf ha docker"
version: "1.0.062"
slug: "ha_docker"
description: "Rf custom Docker service"
url: "https://github.com/kanteruk/hassio-addons/tree/main/ha_docker"

startup: services
boot: auto
init: false

ports:
  8010/tcp: 8010

ports_description:
  8010/tcp: "FastAPI server port"
  
arch:
  - amd64
  - aarch64

options:
  port: 8010
schema:
  port: int
  
map:
  - type: share
    read_only: false
  - type: homeassistant_config
    read_only: false
    path: "/config"
  - type: addon_config
    read_only: false
    path: "/addon_config"
